### ISSUE TITLE
Sentry doesnt show real error.

### ISSUE THREAD

**Issue by ricardoaraujo-hotmart** [getsentry/sentry-webpack-plugin#392] opened 2022-07-26 14:47 UTC
### Environment

How do you use Sentry?
I use @sentry/webpack-plugin to send erros to sentry and my application use react.

Which SDK and version?
@sentry/webpack-plugin: 1.19.0
react :  18.2.0

### Steps to Reproduce

I set up @sentry/webpack-plugin properties

<img width="635" alt="1_Config_plugin" src="https://user-images.githubusercontent.com/82816359/181035530-d464ee72-79bd-4fa1-8529-61c4f660bda1.png">

I simulated an error in my application in react

<img width="635" alt="2_Simulate_error" src="https://user-images.githubusercontent.com/82816359/181035888-40774a56-975a-4709-92c6-e3b328bbf7c3.png">

I saw that the error in sentry is wrong, because dont show me real error, but an error first frame

<img width="635" alt="3_sentry_error" src="https://user-images.githubusercontent.com/82816359/181036117-5801ca49-3b18-4146-af13-139dbdee00d8.png">

Validated sourcemap

<img width="674" alt="4_sourcemap_explain" src="https://user-images.githubusercontent.com/82816359/181036309-4928bdab-8dfc-468b-87f9-190b4ab2ab6e.png">

<img width="635" alt="5_Sentry_sourcemap" src="https://user-images.githubusercontent.com/82816359/181107751-9c21ca6c-db84-4f76-acc1-423192f2b8ec.png">

### Expected Result

I need show me error in Sentry in line that happend, according teste1()  is not defined.

### Actual Result

Show wrong error in the first frame (inicial app component)

**Comment by lforst** [comment] 2023-05-22 12:01
Sorry for not getting back to you. I am closing this because I am in the process of cleaning up the issue stream in this repository. Feel free to open a new issue in case you are still running into this problem - ideally with a reproduction example. Thanks!

**Closed by lforst** 2023-05-22 12:01 UTC
