### ISSUE TITLE
Build failed in 1.3.0 release

### ISSUE THREAD

**Issue by sergej-s** [getsentry/sentry-webpack-plugin#23] opened 2018-01-17 15:49 UTC
Hi! I got the next error when updated plugin to 1.3.0 version:

ERROR in ./node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js
Module parse failed: Unterminated string constant (2:25)
You may need an appropriate loader to handle this file type.
| global.SENTRY_RELEASE={};
| global.SENTRY_RELEASE.id="function release(hash) {
|       return 'FE_' + hash.slice(0, 8);
|     }";

Why does this happen?

**Comment by HazAT** [comment] 2018-01-17 16:02
Hey, can you remove the release key from you `SentryCliPlugin` webpack config.

```
 new SentryCliPlugin({
      release: function release(hash) {
             return 'FE_' + hash.slice(0, 8);
      },
    })
```

Sorry, we introduced a breaking change there.

**Comment by sergej-s** [comment] 2018-01-17 16:21
After removing release I got another weird issue
```
ERROR in ./src/client/init.js
Module parse failed: Unexpected token (57:4)
You may need an appropriate loader to handle this file type.
|   const store = configureStore(window.__INITIAL_STATE__, __DEBUG__);
|   const node = (
|     <App store={store}
|         debug={__DEBUG__}
|         debugExternal={__DEBUG_NW__}/>
 @ multi ./node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js babel-polyfill ./src/client/init.js
```

**Comment by sergej-s** [comment] 2018-01-17 16:39
Why did you consider to create your own release generating func? What do you mean "more correct"?
I am using webpack hash with little prefix.

**Comment by HazAT** [comment] 2018-01-17 17:22
As the readme says, we are now using `sentry-cli releases propose-version` which takes the git commit hash because this is how the release feature was designed to work in Sentry.
Can you give us a rough overview of your stack so we can reproduce this issue?

**Comment by jarnell** [comment] 2018-01-17 17:50
I'm getting a similar error in my React project. It complains about my first JSX opening tag (<), so it seems like the plugin affects my loaders somehow. This is how I add it:

```
new SentryWebpackPlugin({
  release: 'test_1',
  include: './dist',
  ignore: ['node_modules'],
}),
...
```

Rolling back to version 1.2.0 solved it for me.

**Comment by HazAT** [comment] 2018-01-17 18:45
This issue has been fixed in `1.3.1`, when our build in travis is finished please update, the problem should be gone.

**Closed** 2018-01-17 18:44 UTC

**Comment by macnibblet** [comment] 2018-01-17 19:09
Thanks! we can into this problem today as well.

**Comment by sergej-s** [comment] 2018-01-18 15:53
Works with 1.3.2, thanks.

Should I set release string in Raven.js config now or it is configured automatically with sentry-webpack-plugin v1.3.2?

**Comment by HazAT** [comment] 2018-01-18 20:20
So if you are using the latest raven-js version, we set it automagically for you 👍 
Of course you can always overwrite it.
